receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  probabilistic_sampler/logs:
    sampling_percentage: 0

  tail_sampling:
    decision_wait: 10s
    num_traces: 10
    expected_new_traces_per_sec: 10
    policies:
      [
        {
          name: test-policy-1,
          type: always_sample
        },
      ]

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [probabilistic_sampler/logs]
      # processors: [tail_sampling]
      exporters: [debug]
    traces:
      receivers: [otlp]
      # processors: [tail_sampling]
      exporters: [debug]
