receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  probabilistic_sampler/logs:
    sampling_percentage: 0

  probabilistic_sampler:
    sampling_percentage: 15.4
    mode: hash_seed
    hash_seed: 1234

  # tail_sampling:
  #   decision_wait: 10s
  #   num_traces: 100
  #   expected_new_traces_per_sec: 1
  #   decision_cache:
  #     sampled_cache_size: 100_000
  #     non_sampled_cache_size: 100_000
  #   policies:
  #     [
  #       {
  #         name: errors,
  #         type: status_code,
  #         status_code: {status_codes: [ERROR]}
  #       },
  #       {
  #         name: prob-10,
  #         type: probabilistic,
  #         probabilistic: {sampling_percentage: 10}
  #       },
  #     ]

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      # processors: [probabilistic_sampler/logs]
      exporters: [debug]
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler]
      exporters: [debug]
